version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: docker/Dockerfile
    # environment:
    #   spring.datasource.url: jdbc:sqlserver://db
    #   spring.datasource.username: sa
    #   spring.datasource.password: 4Jgz2HmDKS
    ports:
      - 8080:8080
    # depends_on:
    #   - db