version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=4Jgz2HmDKS
      - MSSQL_PID=Developer
    ports:
      - "5433:1433"
    volumes:
      - sqlserver_volume:/var/opt/mssql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  sqlserver_volume: